name: solution
description: Affiche un message et un lien en cas d'échec du build
runs:
  using: composite
  steps:
    - name: Message
      shell: bash
      run: |
        echo "::group::Solution"
        echo "Build échoué. Mais La solution est simple : https://www.youtube.com/watch?v=dQw4w9WgXcQ"
        echo "::endgroup::"
